### ISSUE TITLE
Log pulp's task id

### ISSUE THREAD

**Issue by pbabinca** [projectatomic/atomic-reactor#263]
After dockpulp submits task to pulp log it in atomic-reactor. This will be helpful for debugging problems where atomic-reactor ends up stuck on push_to_pulp plugin.

**Comment by twaugh** [comment]
The `pulp_push` plugin has a parameter `dockpulp_loglevel`, so we ought to be able to adjust the `prod_inner.json` in osbs-client so that it says:

```
"dockpulp_loglevel": 10
```

in the `pulp_push` section.

**Comment by pbabinca** [comment]
Can this be set in configuration?

Do I understand it correctly that atomic-reactor will rely on dockpulp to print pulp's task id in this loglevel?

**Comment by twaugh** [comment]
It has to be set in the build JSON -- there's no `osbs.conf` configuration directive for it.

That capability went into atomic-reactor 1.4.0 (https://github.com/projectatomic/atomic-reactor/pull/214).

You need to edit the `prod_inner.json` file so that the `pulp_push` section reads:

```
    {
      "name": "pulp_push",
      "args": {
        [...],
        "dockpulp_loglevel": 10
      }
    },
```

This will produce lots of debugging information, however.

The real fix will be for the plugin to log the task ID, as you originally reported. Just wanted to note that you can get that task ID currently, without the need for code changes.

**Comment by pbabinca** [comment]
In my case this is harder to set - it would mean change json and rebuild the package and deploy it on prod server. Configuration change of osbs is easier to deploy.

So
