### ISSUE TITLE
pulp plugin: don't use push_to_pulp

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/atomic-reactor#354]
It's going to be removed from upstream; let's remove the call by "moving" the method to our codebase.

**Comment by mmilata** [comment]
@breillyrh, is this still the plan with dockpulp?

**Comment by breillyrh** [comment]
Yes.

**Comment by mmilata** [comment]
@breillyrh, got some more questions.

We use cert+key in atomic-reactor to authenticate to pulp. However current dockpulp master doesn't allow the library user to provide cert+key and only appears to support login+password. Can you provide such capability, for example by cherry-picking midnightercz/dockpulp@e9ec1f8f080c158df76ef7875999cb18ece8672d?

Second question, what specifically are you planning to remove from dockpulp? Just `push_tar_to_pulp`? What about `crane` and `watch_tasks` which we also use?

**Comment by breillyrh** [comment]
I don't see any reason to not include the cert+key capability - I can add that from what's in that commit.

Just push_tar_to_pulp. Crane and watch_tasks are needed for the CLI/rel-eng use.

**Comment by mmilata** [comment]
Great!

Jindra also rewrote `watch_tasks` to return as soon as any of the tasks fails (https://github.com/midnightercz/dockpulp/blob/push_to_pulp_perf/dockpulp/__init__.py#L905), which significantly improves user experience:) Would you mind bringing that code into master, or at least the `deleteTask` method (midnightercz/dockpulp@1f51708e4b87c4be0a4f939637c32329a78c1e2e) so that we can reimplement it in atomic-reactor?

**Comment by mmilata** [comment]
@breillyrh, forgot to hilight you in the previous message^.

**Comment by breillyrh** [comment]
@mmilata I see no problem with that, I can bring it into master.
